package com.ehr.dao;

import com.ehr.model.Emp;
import java.util.List;

public interface EmpDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Wed Jun 26 10:38:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Wed Jun 26 10:38:50 CST 2019
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Wed Jun 26 10:38:50 CST 2019
     */
    Emp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Wed Jun 26 10:38:50 CST 2019
     */
    List<Emp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Wed Jun 26 10:38:50 CST 2019
     */
    int updateByPrimaryKey(Emp record);
}