server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/View/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/ym-ehr-oa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
# Mybatis配置
mybatis:
  typeAliasesPackage: com.ehr.model
  mapperLocations: classpath:com/ehr/dao/mapper/*.xml
